// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://metaxsywmbchztqswftn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldGF4c3l3bWJjaHp0cXN3ZnRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwODMwMDQsImV4cCI6MjA1NTY1OTAwNH0.IkHAIi03ZdAMA2dLkHSP44wb0Co-cuMW2LPWx4ibnqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);